# Generated by Django 5.0.3 on 2024-05-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iut', '0002_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('filiere', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='memoires/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
