# Generated by Django 5.0.3 on 2024-05-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iut', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adresse_email',
            new_name='email',
        ),
    ]
